### ISSUE TITLE
javascript syntax bug

### ISSUE THREAD

**Issue by bishtsurajsoftage** [bishtsurajsoftage/random#35]
There is a syntax error on line 7 of main app.js file and there is also unnecessary code after line 12.

**Comment by bishtsurajsoftage** [comment]
There is error in code of index file.

**Comment by adisoftage** [comment]
Have fixed the unnecesary code after 12 and optimized th ecode

**Comment by bishtsurajsoftage** [comment]
Please resolve the error as soon as possible.

> Have fixed the unnecesary code after 12 and optimized th ecode



> Have fixed the unnecesary code after 12 and optimized th ecode



> Have fixed the unnecesary code after 12 and optimized th ecode

well please resolve the issue as soon as possible
